### PR TITLE
Add dotenv support

### PR DESCRIPTION
**Pull request by jswinarton**
Small pull request to add support for loading environment variables from `.env`. Developers can copy `.env-dist` to `.env` on their first clone to get a consistent copy of env variables suitable for local development.

`.env` has been added to a `.dockerignore` file to prevent this from happening on Docker deploys, since Docker has its own way of handling `.env` files.

### CODE REVIEW

**Comment by birdsarah** [comment]
@jswinarton I previously looked at the dotenv crate and chose not to use it because:
- it says "Achtung! This is a v0.* version! Expect bugs and issues all around. Submitting pull requests and issues is highly encouraged!"
- it hasn't been updated in 2 years
- i don't see what this gets us (happy to be persusaded / educated)

On my local instance, I have a `.env` file and I just run `source .env` before running my code. 

My understanding is we don't want to use dotenv on infra run servers, which is why you've added a dockerignore. 
So I don't understand what plus this gets us; and on the downside it adds a dependency and extra code. 

I'm happy to add a `.env.example` file as a developer convenience so they don't have to figure out what files are useful.

In the not too distant future we're likely going to be dealing with environment variables for the test run on gh workflow. I'd like to not get in the guardian situation where a developer has to remember to add envvars in a bunch of different places. I don't have a solution off the top of my head.

**Review by birdsarah — CHANGES_REQUESTED** [review]
marking as "request changes" but what i really want is a discussion about the benefits / an elegant way of handling envvars in one place.

**Comment by birdsarah** [comment]
@bwells-moz let us know if you have any opinions about this.

**Comment by jswinarton** [comment]
Hey, these are all good points and I don't have any objections to choosing a different path. My reasoning (which admittedly I didn't spend a lot of time thinking through) was that a lot of the official docs and tutorials for official libs like actix and diesel use dotenv themselves, implying it gets a solid amount of use elsewhere and is thus "vetted" in a sense.

But there are other perfectly good ways of accomplishing the same thing. Your method is nice because it doesn't involve changing production code for purely local considerations. The most important thing to me is that we have a "no think" way of getting the app running on a local machine that doesn't involve any futzing around with configuration. From that perspective the most important thing is the `.env.example` file and good README documentation. I do find remembering to call `source .env` mildly annoying but it's not a dealbreaker.

The other option, which I've seen used to decent effect on other projects, is to add a Makefile that sources the environment at the top and then you call `make run` where you would have called `cargo run` before. Maybe this is overkill here. Your call.

> In the not too distant future we're likely going to be dealing with environment variables for the test run on gh workflow. I'd like to not get in the guardian situation where a developer has to remember to add envvars in a bunch of different places. I don't have a solution off the top of my head.

I agree that this sucks and I have never personally found a good solution for it other than straight up quitting the app immediately if all the necessary environment variables aren't in place and have reasonable values. Which you've already done. But in practice I've always found there is at least some divergence between a local env setup and CI, which means that the duplication is necessary. You could potentially have CI "inherit" the `.env.example` file and then override only the ones that need to be different. But then you're in the situation of having to read two different files to get the whole picture. :woozy_face:

**Comment by jswinarton** [comment]
So. I know I'm out until Monday and I don't want to slow down work on this. @birdsarah if you still want to go with the source .env method, I think the right thing to do would be to strip out the `dotenv` stuff here and change the README to say something like `. .env && cargo run` where we had just `cargo run` before or something similar. Then this can be merged into #13 and it shouldn't cause any issues. Feel free to continue work on that one if you need to.

**Comment by birdsarah** [comment]
Closing. Using zero2prod recommendation of config and opening a new PR.

**Pull request closed without merging**
